name: nexus_flutter_app
description: Nexus AI Focus Predictor Flutter Client
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.1.1
  fl_chart: ^0.65.0 # For radar and line charts
  shared_preferences: ^2.2.1 # For persisting session state if needed
  flutter_secure_storage: ^9.2.2 # Secure token storage
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
